env:
  browser: true
  es2021: true
  commonjs: true
extends: 
  # - 'eslint:recommended'
  - 'plugin:vue/vue3-recommended'
  - 'prettier'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 13
  sourceType: 'module'
plugins:
  - 'vue'
  - 'html'
  - 'prettier'
rules:
  prettier/prettier:
  - 'warn'
  - singleQuote: true
    semi: true
