env:
  browser: true
  es2021: true
  commonjs: true
  node: true
extends: 
  - 'eslint:recommended'
  - '@vue/typescript/recommend'
  - 'prettier'
  # - 'plugin:vue/vue3-recommended'
  # - 'plugin:@typescipt-eslint/eslint-recommend'
  # - 'plugin:@typescipt-eslint/recommend'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
plugins:
  - 'vue'
  - 'html'
  - 'prettier'
  # - '@typescript-eslint'
rules:
  prettier/prettier:
  - 'warn'
  - singleQuote: true
    semi: false
