root: true
env:
  browser: true
  es2021: true
  commonjs: true
extends: 
  - 'eslint:recommended'
  - 'plugin:vue/vue3-essential'
  - '@vue/eslint-config-typescript'
  - 'prettier'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
plugins:
  - 'vue'
  - 'html'
  - 'prettier'
rules:
  prettier/prettier:
    - 'warn'
    - singleQuote: true
      semi: false
